language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t jkoshley/docker-react -f Dockerfile.dev .

script:
  -docker run -e CI=true jkoshley/docker-react npm run test